## Load Dataset
This dataset contains online retail transactions, including invoice, product, quantity, price, customer, and country details. It will be used to analyze customer behavior and prepare for segmentation and retention analysis.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('~/Customer-Segmentation-and-Churn-Analysis/data/online_retail.csv')

## Dataset Understanding
Preview the dataset, check data types, and identify any missing values.

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [5]:
df.shape

(541909, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [7]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [8]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

## Data Granularity
Each row represents a single product within an invoice, so one invoice can appear multiple times.

## Business Context
This project analyzes customer purchasing behavior to uncover spending patterns and customer activity.

Key Questions:
- Who are the top customers by spending?
- Who are the most frequent customers?
- Which customers are at risk of churn?
- Which customers contribute the highest revenue?

## Data Cleaning

In [10]:
# Initial dataset shape
print("Original dataset shape:", df.shape)

Original dataset shape: (541909, 8)

In [11]:
# Remove rows without CustomerID, since they cannot be used for customer analysis
df = df.dropna(subset=['CustomerID'])

In [12]:
# Remove duplicate records to avoid repeated transactions
df = df.drop_duplicates()

In [13]:
# Convert InvoiceDate to datetime format for time-based analysis
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [14]:
# Remove rows with negative quantities (usually returned items)
df = df[df["Quantity"] > 0]

# Remove rows with zero or negative prices to ensure valid sales data
df = df[df['UnitPrice'] > 0]

In [15]:
# Final dataset shape
print("Cleaned dataset shape:", df.shape)

Cleaned dataset shape: (392692, 8)

In [16]:
# Save the cleaned dataset to a CSV file
df.to_csv("~/customer_segmentation_churn/data/cleaned_data.csv",index = False)

## Conclusion
- The dataset was explored to understand its structure, features, and business context.
- Data quality issues such as missing values, duplicates, and inconsistencies were identified and handled.
- Necessary preprocessing steps were applied, including data type corrections and feature preparation.
- The cleaned dataset is now ready for exploratory data analysis and further modeling.